version: "3"
services:
  rookie_database:
    container_name: rookie_database
    image: postgis/postgis:13-master
    volumes:
      - ./backend/data/database:/var/lib/postgresql/data
    networks:
      - rookie_directus
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  directus:
    container_name: rookie_directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./backend/uploads:/directus/uploads
    networks:
      - rookie_directus
      - rookie_frontend
    depends_on:
      - rookie_database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "rookie_database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      CORS_ENABLED: "true"
  
  frontend:
    container_name: rookie_frontend
    image: directus/directus:latest
    ports:
      - 4200:4200
    networks:
      - rookie_frontend
      
networks:
  rookie_directus:
  rookie_frontend: